import { applyLookProfile } from './look-profiles.js';

export const STYLE_PRESETS = Object.freeze({
  'unknown-planet': {
    label: 'unknown planet',
    mode: 'sphere',
    look: 'clean',
    values: {
      fieldScale: 1,
      fieldDepth: 0.9,
      fieldStereo: 0.25,
      fieldTwist: 0.12,
      fieldCurl: 0,
      fieldFlow: 0.16,
      fieldSymmetry: 4,
      fieldHistory: 0.96,
      fieldRotation: 0.15,
      morph: 0.08,
      cameraShot: 'hero',
      cameraMotion: 'drift',
      cameraAmount: 0.22,
    },
  },
  'ps2-temple': {
    label: 'PS2 signal temple',
    mode: 'cathedral',
    look: 'ps2-480',
    values: {
      fieldScale: 0.9,
      fieldDepth: 1.35,
      fieldStereo: 0.6,
      fieldTwist: 0.1,
      fieldCurl: 0,
      fieldFlow: 0.12,
      fieldSymmetry: 6,
      fieldHistory: 0.86,
      fieldRotation: 0,
      morph: 0.35,
      cameraShot: 'auto',
      cameraMotion: 'pendulum',
      cameraAmount: 0.18,
    },
  },
  'scope-kiss': {
    label: 'oscilloscope kiss',
    mode: 'ribbon',
    look: 'clean',
    values: {
      fieldScale: 1.15,
      fieldDepth: 1.4,
      fieldStereo: 1.8,
      fieldTwist: 0.8,
      fieldCurl: 0.35,
      fieldFlow: 0.4,
      fieldSymmetry: 2,
      fieldHistory: 0.72,
      fieldRotation: 0,
      morph: 0,
      cameraShot: 'horizon',
      cameraMotion: 'rail',
      cameraAmount: 0.35,
    },
  },
  'milkdrop-memory': {
    label: 'milkdrop memory',
    mode: 'tunnel',
    look: 'ghost',
    values: {
      fieldScale: 1.05,
      fieldDepth: 1.7,
      fieldStereo: 1.15,
      fieldTwist: 1.25,
      fieldCurl: 0.25,
      fieldFlow: 0.8,
      fieldSymmetry: 5,
      fieldHistory: 1.18,
      fieldRotation: 0.28,
      morph: 0.75,
      cameraShot: 'hero',
      cameraMotion: 'orbit',
      cameraAmount: 0.42,
    },
  },
  'demoscene-fold': {
    label: 'demoscene fold',
    mode: 'topology',
    look: 'ps2-240',
    values: {
      fieldScale: 1,
      fieldDepth: 1.05,
      fieldStereo: 0.85,
      fieldTwist: 1.4,
      fieldCurl: 0.7,
      fieldFlow: 0.55,
      fieldSymmetry: 7,
      fieldHistory: 0.9,
      fieldRotation: 0.4,
      morph: 0.7,
      cameraShot: 'side',
      cameraMotion: 'orbit',
      cameraAmount: 0.28,
    },
  },
  'sonar-bloom': {
    label: 'sonar bloom',
    mode: 'polar',
    look: 'tape',
    values: {
      fieldScale: 0.92,
      fieldDepth: 1.25,
      fieldStereo: -0.8,
      fieldTwist: 0.65,
      fieldCurl: -0.1,
      fieldFlow: -0.22,
      fieldSymmetry: 3,
      fieldHistory: 0.78,
      fieldRotation: -0.08,
      morph: 0.18,
      cameraShot: 'overhead',
      cameraMotion: 'drift',
      cameraAmount: 0.3,
    },
  },
  'spectral-canyon': {
    label: 'spectral canyon',
    mode: 'bowl',
    look: 'clean',
    values: {
      fieldScale: 1.1,
      fieldDepth: 1.9,
      fieldStereo: 1,
      fieldTwist: -0.25,
      fieldCurl: 0,
      fieldFlow: 0.08,
      fieldSymmetry: 4,
      fieldHistory: 0.62,
      fieldRotation: 0,
      morph: 0.15,
      bowlExp: 2.8,
      cameraShot: 'auto',
      cameraMotion: 'still',
    },
  },
  'dub-wire': {
    label: 'dub wire memory',
    mode: 'wave',
    look: 'tape',
    values: {
      fieldScale: 1,
      fieldDepth: 1.5,
      fieldStereo: 1.35,
      fieldTwist: 0.45,
      fieldCurl: 0.2,
      fieldFlow: 0.28,
      fieldSymmetry: 4,
      fieldHistory: 1.28,
      fieldRotation: 0,
      morph: 0.3,
      cameraShot: 'horizon',
      cameraMotion: 'drift',
      cameraAmount: 0.25,
    },
  },
});

export function applyStylePreset(project, id) {
  const preset = STYLE_PRESETS[id] ?? STYLE_PRESETS['unknown-planet'];
  Object.assign(project, preset.values);
  applyLookProfile(project, preset.look);
  project.previewOutput = preset.look !== 'clean';
  return preset.mode;
}
